### ISSUE TITLE
Event Detail Page - Tickets - Only 1 ticket type showing (Provide user feedback on event creation)

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#783] opened 2018-12-21 23:56 UTC
When there are multiple tickets types available only one is listed on the event page

**Comment by Jasonvdb** [comment] 2018-12-23 08:49
@zmelamed seems like the issue is that there is no active price point for the ticket type so the API won't return it.

The sale time and sale end time of the ticket type is correct but the price point dates were edited and the current date doesn't fall in that range. It is behaving as designed but I can imagine clients having this query often. 

Maybe we should add some design element to the admin event editing page that explains why each ticket type is or is not available for sale? 

(Noticed the layout for that date/time picker behaves incorrectly, will make a separate issue for that)

<img width="992" alt="screenshot 2018-12-23 at 10 41 02" src="https://user-images.githubusercontent.com/5300488/50382058-552ba080-069f-11e9-9344-0d6d5418d648.png">

**Comment by ryanjoconnor** [comment] 2018-12-23 20:16
> @zmelamed seems like the issue is that there is no active price point for the ticket type so the API won't return it.
> 
> The sale time and sale end time of the ticket type is correct but the price point dates were edited and the current date doesn't fall in that range. It is behaving as designed but I can imagine clients having this query often.
> 
> Maybe we should add some design element to the admin event editing page that explains why each ticket type is or is not available for sale?
> 
> (Noticed the layout for that date/time picker behaves incorrectly, will make a separate issue for that)
> 
> <img alt="screenshot 2018-12-23 at 10 41 02" width="992" src="https://user-images.githubusercontent.com/5300488/50382058-552ba080-069f-11e9-9344-0d6d5418d648.png">

@zmelamed @Jasonvdb @CjS77 

We need to do a better job guiding the user through errors like this. There are also too many independent variables when creating ticket types that are going to lead to user error. Here are others: 

Every ticket type's Sale End Time needs to be equal to the Event Door Time. Right now we're defaulting to 12pm. Ticket volumes spike the day of the show right up until doors. 

Sale Start Time is ambiguous. Does the user need to include one? What's the default?  

We need to eliminate the scroll feature across the board. Sale Start Time in this example is 12:46. Clearly (my) user error. Someone WILL do this on more important variables like quantity and price. If an agent sees a published ticket price they didn't agree with, they are going to call our client and it's going to be a problem.

**Comment by zmelamed** [comment] 2018-12-24 04:04
One real quick point that’s an error in the implementation.

If I create a ticket that’s $5, and theres a sale start and end date for that ticket, the price for that ticket should be $5 unless there is an “Auto Price Points” change to over ride it. The auto price point changes are overrides to the face value of the ticket, and should never stop the ticket type from displaying.

**Comment by Jasonvdb** [comment] 2018-12-28 11:41
@zmelamed so the fact that one ticket type displays isn't technically a bug but I'm keeping this issue open. Will you comment here when you have an idea of how to be more proactive with the feedback on event creation? Then I'll hop right on this.

**Comment by zmelamed** [comment] 2018-12-28 15:14
I want to make sure it's clear that the VIP ticket type should have been displayed at a $5 price, it's not implemented properly. In my book this is a bug, and better user feedback doesn't resolve it, but regardless of what we label it it needs to be fixed.

Auto price changes are overrides to the ticket price, it should have been showing the VIP ticket at $5 (the face value of the ticket) because there was no auto price point set to override it.

**Comment by Jasonvdb** [comment] 2018-12-28 16:45
Ok I see what's going on now, sorry originally I thought maybe we were talking about 2 separate issues.

I see the problem now. The way it currently works is these price points aren't overrides for default values, the api is only looking at price points to determine what to display. In the web, when you're editing the price for a ticket type, you're actually editing the price for the default price point that's just hidden from view. Currently there is no price set on a ticket level, only price point level. 

I think we'll need more of an api change to make price points overrides for default values but I'll chat to @Krakaw and @mikethetike.

**Comment by Krakaw** [comment] 2018-12-31 08:09
@zmelamed I get what you are looking for, I'm busy adding it into the API big-neon/bn-api#817

**Comment by Jasonvdb** [comment] 2019-01-02 12:43
Closed in #842

**Closed by Jasonvdb** 2019-01-02 12:43 UTC
Labels: Observed Bug, Urgent, bug, enhancement, in progress
