### ISSUE TITLE
Fan Profile Management: Redesign: Activity Items: Ticket Transfer (3 states)

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1509] opened 2019-06-03 09:29 UTC
Each state includes:

* Tickets
  * Ticket ID (Order # Link To Order)
* Initiated By
  * Transferrer Name
  * Date/Time
* Transfer Address
  * Email/Phone number transfer was sent to
- **Successful State:**
  - Accepted By
    - User Name
    - Date/Time
- **Pending**
  - If admin or higher:
    - CTA: Cancel Transfer
      - When Clicked the they should confirm the cancel transfer action
- **Cancelled**
  - Cancelled By
    - User Name
    - Date/Time

**Comment by Anziskavds** [comment] 2019-07-23 07:18
Tested on develop and some of the fields tested unsuccessful.

Steps to reproduce:

- Ticket transfer (3 states) each state incl:
Tickets
Ticket ID (Order # Link To Order)
- Initiated By
Transferrer Name
**Date/Time? - Doesn't show**
Transfer Address
Email/Phone number transfer was sent to
https://cl.ly/b67072fb934b
- Ticket transfer Successful State:
Accepted By
User Name
**Date/Time? - Doesn't show**
- Ticket transfer Cancelled state:
**Cancelled By**
**User Name**
**Date/Time**
None of the above shows
https://cl.ly/b2895765358e

**Comment by Anziskavds** [comment] 2019-07-24 10:37
- Tested unsuccessful on develop.
- Successful State:
**Accepted By**
User Name
**Date/Time - Doesn't show**
- Ticket transfer Cancelled state:
**Cancelled By**
User Name
**Date/Time - Doesn't show**

**Comment by Anziskavds** [comment] 2019-07-26 11:29
Tested successful on develop for web and mobile web

**Comment by Anziskavds** [comment] 2019-07-31 08:46
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment] 2019-08-01 13:24
Tested unsuccessful on Prod for web and mobile web.

Steps to reproduce:

- On a pending transfer the date and time shouldn't reflect under accepted by because it wasn't accepted yet. Only after the transfer was accepted it should show the date and time under accepted by along with the users name who accepted the transfer.

https://cl.ly/92f05de650b2
https://cl.ly/ed14593403ac

**Comment by shanimal08** [comment] 2019-08-01 14:11
Eek, sorry, I messed that up when I added in the check for cancelled_by today.. changed too much! On it

**Comment by Anziskavds** [comment] 2019-08-05 08:46
Tested successful on develop and beta on web and mobile web. Still unsuccessful on Prod. @shanimal08

**Comment by Anziskavds** [comment] 2019-08-05 11:33
Prod tested successful on web and mobile web.

**Closed by Anziskavds** 2019-08-05 11:33 UTC
